### ISSUE TITLE
What are DigiAssets video

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DigiByte.org#67]
A simplified way to create digital assets.

No translation needed.
Recommend removing the "What are DigiAssets video". The issue is that DigiByte mobile apps need to be purged from the website, this video promotes the mobile wallet. It says, “you can safely store and create DigiAssets with your DigiByte mobile wallet". The mobile wallet doesn’t support the current v3 DigiAssets to include the issues mentioned in issue #59 about the mobile wallet. Recommend replacing with temporary image placeholder until a different video is created.

![Screenshot 2023-07-01 174607](https://github.com/DigiByte-Core/DGBio/assets/136190014/b7f81f4b-8932-4dd6-8e71-b490e96c3b2e)

**Comment by Sbosvk** [comment]
I think that maybe we can technically feel safe with this one by just pretending that we are not talking about THE DigiByte Mobile wallet, but rather A DigiByte Mobile wallet. It is a bit misleading of course, but it would be a shame to have to remove this video because of this. Video contains no links or pointers to the actually discontinued application. I think it's a matter of perspective. Someone who has never used or heard of the DigiByte Mobile wallet might not even make the connection.

**Comment by DGBNOOB** [comment]
Thank you for your input, I will close the issues pertaining to the videos. Maybe in the future, if we can get updated videos then we can revisit and reconsider replacing the current videos on the website.
